<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PaysSeeder extends Seeder
{
    public function run(): void
    {
        $pays = [
            // ── AFRIQUE ──
            ['code_iso2'=>'CM','code_iso3'=>'CMR','nom'=>'Cameroun','indicatif_telephone'=>'+237','drapeau_emoji'=>'🇨🇲','continent'=>'Afrique','ordre'=>1],
            ['code_iso2'=>'DZ','code_iso3'=>'DZA','nom'=>'Algérie','indicatif_telephone'=>'+213','drapeau_emoji'=>'🇩🇿','continent'=>'Afrique'],
            ['code_iso2'=>'AO','code_iso3'=>'AGO','nom'=>'Angola','indicatif_telephone'=>'+244','drapeau_emoji'=>'🇦🇴','continent'=>'Afrique'],
            ['code_iso2'=>'BJ','code_iso3'=>'BEN','nom'=>'Bénin','indicatif_telephone'=>'+229','drapeau_emoji'=>'🇧🇯','continent'=>'Afrique'],
            ['code_iso2'=>'BW','code_iso3'=>'BWA','nom'=>'Botswana','indicatif_telephone'=>'+267','drapeau_emoji'=>'🇧🇼','continent'=>'Afrique'],
            ['code_iso2'=>'BF','code_iso3'=>'BFA','nom'=>'Burkina Faso','indicatif_telephone'=>'+226','drapeau_emoji'=>'🇧🇫','continent'=>'Afrique'],
            ['code_iso2'=>'BI','code_iso3'=>'BDI','nom'=>'Burundi','indicatif_telephone'=>'+257','drapeau_emoji'=>'🇧🇮','continent'=>'Afrique'],
            ['code_iso2'=>'CV','code_iso3'=>'CPV','nom'=>'Cap-Vert','indicatif_telephone'=>'+238','drapeau_emoji'=>'🇨🇻','continent'=>'Afrique'],
            ['code_iso2'=>'CF','code_iso3'=>'CAF','nom'=>'République centrafricaine','indicatif_telephone'=>'+236','drapeau_emoji'=>'🇨🇫','continent'=>'Afrique'],
            ['code_iso2'=>'TD','code_iso3'=>'TCD','nom'=>'Tchad','indicatif_telephone'=>'+235','drapeau_emoji'=>'🇹🇩','continent'=>'Afrique'],
            ['code_iso2'=>'KM','code_iso3'=>'COM','nom'=>'Comores','indicatif_telephone'=>'+269','drapeau_emoji'=>'🇰🇲','continent'=>'Afrique'],
            ['code_iso2'=>'CG','code_iso3'=>'COG','nom'=>'Congo','indicatif_telephone'=>'+242','drapeau_emoji'=>'🇨🇬','continent'=>'Afrique'],
            ['code_iso2'=>'CD','code_iso3'=>'COD','nom'=>'République démocratique du Congo','indicatif_telephone'=>'+243','drapeau_emoji'=>'🇨🇩','continent'=>'Afrique'],
            ['code_iso2'=>'CI','code_iso3'=>'CIV','nom'=>"Côte d'Ivoire",'indicatif_telephone'=>'+225','drapeau_emoji'=>'🇨🇮','continent'=>'Afrique'],
            ['code_iso2'=>'DJ','code_iso3'=>'DJI','nom'=>'Djibouti','indicatif_telephone'=>'+253','drapeau_emoji'=>'🇩🇯','continent'=>'Afrique'],
            ['code_iso2'=>'EG','code_iso3'=>'EGY','nom'=>'Égypte','indicatif_telephone'=>'+20','drapeau_emoji'=>'🇪🇬','continent'=>'Afrique'],
            ['code_iso2'=>'GQ','code_iso3'=>'GNQ','nom'=>'Guinée équatoriale','indicatif_telephone'=>'+240','drapeau_emoji'=>'🇬🇶','continent'=>'Afrique'],
            ['code_iso2'=>'ER','code_iso3'=>'ERI','nom'=>'Érythrée','indicatif_telephone'=>'+291','drapeau_emoji'=>'🇪🇷','continent'=>'Afrique'],
            ['code_iso2'=>'SZ','code_iso3'=>'SWZ','nom'=>'Eswatini','indicatif_telephone'=>'+268','drapeau_emoji'=>'🇸🇿','continent'=>'Afrique'],
            ['code_iso2'=>'ET','code_iso3'=>'ETH','nom'=>'Éthiopie','indicatif_telephone'=>'+251','drapeau_emoji'=>'🇪🇹','continent'=>'Afrique'],
            ['code_iso2'=>'GA','code_iso3'=>'GAB','nom'=>'Gabon','indicatif_telephone'=>'+241','drapeau_emoji'=>'🇬🇦','continent'=>'Afrique'],
            ['code_iso2'=>'GM','code_iso3'=>'GMB','nom'=>'Gambie','indicatif_telephone'=>'+220','drapeau_emoji'=>'🇬🇲','continent'=>'Afrique'],
            ['code_iso2'=>'GH','code_iso3'=>'GHA','nom'=>'Ghana','indicatif_telephone'=>'+233','drapeau_emoji'=>'🇬🇭','continent'=>'Afrique'],
            ['code_iso2'=>'GN','code_iso3'=>'GIN','nom'=>'Guinée','indicatif_telephone'=>'+224','drapeau_emoji'=>'🇬🇳','continent'=>'Afrique'],
            ['code_iso2'=>'GW','code_iso3'=>'GNB','nom'=>'Guinée-Bissau','indicatif_telephone'=>'+245','drapeau_emoji'=>'🇬🇼','continent'=>'Afrique'],
            ['code_iso2'=>'KE','code_iso3'=>'KEN','nom'=>'Kenya','indicatif_telephone'=>'+254','drapeau_emoji'=>'🇰🇪','continent'=>'Afrique'],
            ['code_iso2'=>'LS','code_iso3'=>'LSO','nom'=>'Lesotho','indicatif_telephone'=>'+266','drapeau_emoji'=>'🇱🇸','continent'=>'Afrique'],
            ['code_iso2'=>'LR','code_iso3'=>'LBR','nom'=>'Libéria','indicatif_telephone'=>'+231','drapeau_emoji'=>'🇱🇷','continent'=>'Afrique'],
            ['code_iso2'=>'LY','code_iso3'=>'LBY','nom'=>'Libye','indicatif_telephone'=>'+218','drapeau_emoji'=>'🇱🇾','continent'=>'Afrique'],
            ['code_iso2'=>'MG','code_iso3'=>'MDG','nom'=>'Madagascar','indicatif_telephone'=>'+261','drapeau_emoji'=>'🇲🇬','continent'=>'Afrique'],
            ['code_iso2'=>'MW','code_iso3'=>'MWI','nom'=>'Malawi','indicatif_telephone'=>'+265','drapeau_emoji'=>'🇲🇼','continent'=>'Afrique'],
            ['code_iso2'=>'ML','code_iso3'=>'MLI','nom'=>'Mali','indicatif_telephone'=>'+223','drapeau_emoji'=>'🇲🇱','continent'=>'Afrique'],
            ['code_iso2'=>'MR','code_iso3'=>'MRT','nom'=>'Mauritanie','indicatif_telephone'=>'+222','drapeau_emoji'=>'🇲🇷','continent'=>'Afrique'],
            ['code_iso2'=>'MU','code_iso3'=>'MUS','nom'=>'Maurice','indicatif_telephone'=>'+230','drapeau_emoji'=>'🇲🇺','continent'=>'Afrique'],
            ['code_iso2'=>'MA','code_iso3'=>'MAR','nom'=>'Maroc','indicatif_telephone'=>'+212','drapeau_emoji'=>'🇲🇦','continent'=>'Afrique'],
            ['code_iso2'=>'MZ','code_iso3'=>'MOZ','nom'=>'Mozambique','indicatif_telephone'=>'+258','drapeau_emoji'=>'🇲🇿','continent'=>'Afrique'],
            ['code_iso2'=>'NA','code_iso3'=>'NAM','nom'=>'Namibie','indicatif_telephone'=>'+264','drapeau_emoji'=>'🇳🇦','continent'=>'Afrique'],
            ['code_iso2'=>'NE','code_iso3'=>'NER','nom'=>'Niger','indicatif_telephone'=>'+227','drapeau_emoji'=>'🇳🇪','continent'=>'Afrique'],
            ['code_iso2'=>'NG','code_iso3'=>'NGA','nom'=>'Nigeria','indicatif_telephone'=>'+234','drapeau_emoji'=>'🇳🇬','continent'=>'Afrique'],
            ['code_iso2'=>'RW','code_iso3'=>'RWA','nom'=>'Rwanda','indicatif_telephone'=>'+250','drapeau_emoji'=>'🇷🇼','continent'=>'Afrique'],
            ['code_iso2'=>'ST','code_iso3'=>'STP','nom'=>'Sao Tomé-et-Principe','indicatif_telephone'=>'+239','drapeau_emoji'=>'🇸🇹','continent'=>'Afrique'],
            ['code_iso2'=>'SN','code_iso3'=>'SEN','nom'=>'Sénégal','indicatif_telephone'=>'+221','drapeau_emoji'=>'🇸🇳','continent'=>'Afrique'],
            ['code_iso2'=>'SC','code_iso3'=>'SYC','nom'=>'Seychelles','indicatif_telephone'=>'+248','drapeau_emoji'=>'🇸🇨','continent'=>'Afrique'],
            ['code_iso2'=>'SL','code_iso3'=>'SLE','nom'=>'Sierra Leone','indicatif_telephone'=>'+232','drapeau_emoji'=>'🇸🇱','continent'=>'Afrique'],
            ['code_iso2'=>'SO','code_iso3'=>'SOM','nom'=>'Somalie','indicatif_telephone'=>'+252','drapeau_emoji'=>'🇸🇴','continent'=>'Afrique'],
            ['code_iso2'=>'ZA','code_iso3'=>'ZAF','nom'=>'Afrique du Sud','indicatif_telephone'=>'+27','drapeau_emoji'=>'🇿🇦','continent'=>'Afrique'],
            ['code_iso2'=>'SS','code_iso3'=>'SSD','nom'=>'Soudan du Sud','indicatif_telephone'=>'+211','drapeau_emoji'=>'🇸🇸','continent'=>'Afrique'],
            ['code_iso2'=>'SD','code_iso3'=>'SDN','nom'=>'Soudan','indicatif_telephone'=>'+249','drapeau_emoji'=>'🇸🇩','continent'=>'Afrique'],
            ['code_iso2'=>'TZ','code_iso3'=>'TZA','nom'=>'Tanzanie','indicatif_telephone'=>'+255','drapeau_emoji'=>'🇹🇿','continent'=>'Afrique'],
            ['code_iso2'=>'TG','code_iso3'=>'TGO','nom'=>'Togo','indicatif_telephone'=>'+228','drapeau_emoji'=>'🇹🇬','continent'=>'Afrique'],
            ['code_iso2'=>'TN','code_iso3'=>'TUN','nom'=>'Tunisie','indicatif_telephone'=>'+216','drapeau_emoji'=>'🇹🇳','continent'=>'Afrique'],
            ['code_iso2'=>'UG','code_iso3'=>'UGA','nom'=>'Ouganda','indicatif_telephone'=>'+256','drapeau_emoji'=>'🇺🇬','continent'=>'Afrique'],
            ['code_iso2'=>'ZM','code_iso3'=>'ZMB','nom'=>'Zambie','indicatif_telephone'=>'+260','drapeau_emoji'=>'🇿🇲','continent'=>'Afrique'],
            ['code_iso2'=>'ZW','code_iso3'=>'ZWE','nom'=>'Zimbabwe','indicatif_telephone'=>'+263','drapeau_emoji'=>'🇿🇼','continent'=>'Afrique'],

            // ── EUROPE ──
            ['code_iso2'=>'FR','code_iso3'=>'FRA','nom'=>'France','indicatif_telephone'=>'+33','drapeau_emoji'=>'🇫🇷','continent'=>'Europe','ordre'=>2],
            ['code_iso2'=>'BE','code_iso3'=>'BEL','nom'=>'Belgique','indicatif_telephone'=>'+32','drapeau_emoji'=>'🇧🇪','continent'=>'Europe'],
            ['code_iso2'=>'CH','code_iso3'=>'CHE','nom'=>'Suisse','indicatif_telephone'=>'+41','drapeau_emoji'=>'🇨🇭','continent'=>'Europe'],
            ['code_iso2'=>'LU','code_iso3'=>'LUX','nom'=>'Luxembourg','indicatif_telephone'=>'+352','drapeau_emoji'=>'🇱🇺','continent'=>'Europe'],
            ['code_iso2'=>'DE','code_iso3'=>'DEU','nom'=>'Allemagne','indicatif_telephone'=>'+49','drapeau_emoji'=>'🇩🇪','continent'=>'Europe'],
            ['code_iso2'=>'IT','code_iso3'=>'ITA','nom'=>'Italie','indicatif_telephone'=>'+39','drapeau_emoji'=>'🇮🇹','continent'=>'Europe'],
            ['code_iso2'=>'ES','code_iso3'=>'ESP','nom'=>'Espagne','indicatif_telephone'=>'+34','drapeau_emoji'=>'🇪🇸','continent'=>'Europe'],
            ['code_iso2'=>'PT','code_iso3'=>'PRT','nom'=>'Portugal','indicatif_telephone'=>'+351','drapeau_emoji'=>'🇵🇹','continent'=>'Europe'],
            ['code_iso2'=>'GB','code_iso3'=>'GBR','nom'=>'Royaume-Uni','indicatif_telephone'=>'+44','drapeau_emoji'=>'🇬🇧','continent'=>'Europe'],
            ['code_iso2'=>'IE','code_iso3'=>'IRL','nom'=>'Irlande','indicatif_telephone'=>'+353','drapeau_emoji'=>'🇮🇪','continent'=>'Europe'],
            ['code_iso2'=>'NL','code_iso3'=>'NLD','nom'=>'Pays-Bas','indicatif_telephone'=>'+31','drapeau_emoji'=>'🇳🇱','continent'=>'Europe'],
            ['code_iso2'=>'AT','code_iso3'=>'AUT','nom'=>'Autriche','indicatif_telephone'=>'+43','drapeau_emoji'=>'🇦🇹','continent'=>'Europe'],
            ['code_iso2'=>'PL','code_iso3'=>'POL','nom'=>'Pologne','indicatif_telephone'=>'+48','drapeau_emoji'=>'🇵🇱','continent'=>'Europe'],
            ['code_iso2'=>'CZ','code_iso3'=>'CZE','nom'=>'Tchéquie','indicatif_telephone'=>'+420','drapeau_emoji'=>'🇨🇿','continent'=>'Europe'],
            ['code_iso2'=>'SK','code_iso3'=>'SVK','nom'=>'Slovaquie','indicatif_telephone'=>'+421','drapeau_emoji'=>'🇸🇰','continent'=>'Europe'],
            ['code_iso2'=>'HU','code_iso3'=>'HUN','nom'=>'Hongrie','indicatif_telephone'=>'+36','drapeau_emoji'=>'🇭🇺','continent'=>'Europe'],
            ['code_iso2'=>'RO','code_iso3'=>'ROU','nom'=>'Roumanie','indicatif_telephone'=>'+40','drapeau_emoji'=>'🇷🇴','continent'=>'Europe'],
            ['code_iso2'=>'BG','code_iso3'=>'BGR','nom'=>'Bulgarie','indicatif_telephone'=>'+359','drapeau_emoji'=>'🇧🇬','continent'=>'Europe'],
            ['code_iso2'=>'GR','code_iso3'=>'GRC','nom'=>'Grèce','indicatif_telephone'=>'+30','drapeau_emoji'=>'🇬🇷','continent'=>'Europe'],
            ['code_iso2'=>'HR','code_iso3'=>'HRV','nom'=>'Croatie','indicatif_telephone'=>'+385','drapeau_emoji'=>'🇭🇷','continent'=>'Europe'],
            ['code_iso2'=>'SI','code_iso3'=>'SVN','nom'=>'Slovénie','indicatif_telephone'=>'+386','drapeau_emoji'=>'🇸🇮','continent'=>'Europe'],
            ['code_iso2'=>'EE','code_iso3'=>'EST','nom'=>'Estonie','indicatif_telephone'=>'+372','drapeau_emoji'=>'🇪🇪','continent'=>'Europe'],
            ['code_iso2'=>'LV','code_iso3'=>'LVA','nom'=>'Lettonie','indicatif_telephone'=>'+371','drapeau_emoji'=>'🇱🇻','continent'=>'Europe'],
            ['code_iso2'=>'LT','code_iso3'=>'LTU','nom'=>'Lituanie','indicatif_telephone'=>'+370','drapeau_emoji'=>'🇱🇹','continent'=>'Europe'],
            ['code_iso2'=>'FI','code_iso3'=>'FIN','nom'=>'Finlande','indicatif_telephone'=>'+358','drapeau_emoji'=>'🇫🇮','continent'=>'Europe'],
            ['code_iso2'=>'SE','code_iso3'=>'SWE','nom'=>'Suède','indicatif_telephone'=>'+46','drapeau_emoji'=>'🇸🇪','continent'=>'Europe'],
            ['code_iso2'=>'NO','code_iso3'=>'NOR','nom'=>'Norvège','indicatif_telephone'=>'+47','drapeau_emoji'=>'🇳🇴','continent'=>'Europe'],
            ['code_iso2'=>'DK','code_iso3'=>'DNK','nom'=>'Danemark','indicatif_telephone'=>'+45','drapeau_emoji'=>'🇩🇰','continent'=>'Europe'],
            ['code_iso2'=>'IS','code_iso3'=>'ISL','nom'=>'Islande','indicatif_telephone'=>'+354','drapeau_emoji'=>'🇮🇸','continent'=>'Europe'],
            ['code_iso2'=>'MT','code_iso3'=>'MLT','nom'=>'Malte','indicatif_telephone'=>'+356','drapeau_emoji'=>'🇲🇹','continent'=>'Europe'],
            ['code_iso2'=>'CY','code_iso3'=>'CYP','nom'=>'Chypre','indicatif_telephone'=>'+357','drapeau_emoji'=>'🇨🇾','continent'=>'Europe'],
            ['code_iso2'=>'AL','code_iso3'=>'ALB','nom'=>'Albanie','indicatif_telephone'=>'+355','drapeau_emoji'=>'🇦🇱','continent'=>'Europe'],
            ['code_iso2'=>'BA','code_iso3'=>'BIH','nom'=>'Bosnie-Herzégovine','indicatif_telephone'=>'+387','drapeau_emoji'=>'🇧🇦','continent'=>'Europe'],
            ['code_iso2'=>'MK','code_iso3'=>'MKD','nom'=>'Macédoine du Nord','indicatif_telephone'=>'+389','drapeau_emoji'=>'🇲🇰','continent'=>'Europe'],
            ['code_iso2'=>'ME','code_iso3'=>'MNE','nom'=>'Monténégro','indicatif_telephone'=>'+382','drapeau_emoji'=>'🇲🇪','continent'=>'Europe'],
            ['code_iso2'=>'RS','code_iso3'=>'SRB','nom'=>'Serbie','indicatif_telephone'=>'+381','drapeau_emoji'=>'🇷🇸','continent'=>'Europe'],
            ['code_iso2'=>'XK','code_iso3'=>'XKX','nom'=>'Kosovo','indicatif_telephone'=>'+383','drapeau_emoji'=>'🇽🇰','continent'=>'Europe'],
            ['code_iso2'=>'MD','code_iso3'=>'MDA','nom'=>'Moldavie','indicatif_telephone'=>'+373','drapeau_emoji'=>'🇲🇩','continent'=>'Europe'],
            ['code_iso2'=>'UA','code_iso3'=>'UKR','nom'=>'Ukraine','indicatif_telephone'=>'+380','drapeau_emoji'=>'🇺🇦','continent'=>'Europe'],
            ['code_iso2'=>'BY','code_iso3'=>'BLR','nom'=>'Biélorussie','indicatif_telephone'=>'+375','drapeau_emoji'=>'🇧🇾','continent'=>'Europe'],
            ['code_iso2'=>'RU','code_iso3'=>'RUS','nom'=>'Russie','indicatif_telephone'=>'+7','drapeau_emoji'=>'🇷🇺','continent'=>'Europe'],
            ['code_iso2'=>'AD','code_iso3'=>'AND','nom'=>'Andorre','indicatif_telephone'=>'+376','drapeau_emoji'=>'🇦🇩','continent'=>'Europe'],
            ['code_iso2'=>'MC','code_iso3'=>'MCO','nom'=>'Monaco','indicatif_telephone'=>'+377','drapeau_emoji'=>'🇲🇨','continent'=>'Europe'],
            ['code_iso2'=>'SM','code_iso3'=>'SMR','nom'=>'Saint-Marin','indicatif_telephone'=>'+378','drapeau_emoji'=>'🇸🇲','continent'=>'Europe'],
            ['code_iso2'=>'VA','code_iso3'=>'VAT','nom'=>'Vatican','indicatif_telephone'=>'+379','drapeau_emoji'=>'🇻🇦','continent'=>'Europe'],
            ['code_iso2'=>'LI','code_iso3'=>'LIE','nom'=>'Liechtenstein','indicatif_telephone'=>'+423','drapeau_emoji'=>'🇱🇮','continent'=>'Europe'],

            // ── AMÉRIQUE ──
            ['code_iso2'=>'US','code_iso3'=>'USA','nom'=>'États-Unis','indicatif_telephone'=>'+1','drapeau_emoji'=>'🇺🇸','continent'=>'Amérique'],
            ['code_iso2'=>'CA','code_iso3'=>'CAN','nom'=>'Canada','indicatif_telephone'=>'+1','drapeau_emoji'=>'🇨🇦','continent'=>'Amérique'],
            ['code_iso2'=>'MX','code_iso3'=>'MEX','nom'=>'Mexique','indicatif_telephone'=>'+52','drapeau_emoji'=>'🇲🇽','continent'=>'Amérique'],
            ['code_iso2'=>'BR','code_iso3'=>'BRA','nom'=>'Brésil','indicatif_telephone'=>'+55','drapeau_emoji'=>'🇧🇷','continent'=>'Amérique'],
            ['code_iso2'=>'AR','code_iso3'=>'ARG','nom'=>'Argentine','indicatif_telephone'=>'+54','drapeau_emoji'=>'🇦🇷','continent'=>'Amérique'],
            ['code_iso2'=>'CL','code_iso3'=>'CHL','nom'=>'Chili','indicatif_telephone'=>'+56','drapeau_emoji'=>'🇨🇱','continent'=>'Amérique'],
            ['code_iso2'=>'CO','code_iso3'=>'COL','nom'=>'Colombie','indicatif_telephone'=>'+57','drapeau_emoji'=>'🇨🇴','continent'=>'Amérique'],
            ['code_iso2'=>'PE','code_iso3'=>'PER','nom'=>'Pérou','indicatif_telephone'=>'+51','drapeau_emoji'=>'🇵🇪','continent'=>'Amérique'],
            ['code_iso2'=>'VE','code_iso3'=>'VEN','nom'=>'Venezuela','indicatif_telephone'=>'+58','drapeau_emoji'=>'🇻🇪','continent'=>'Amérique'],
            ['code_iso2'=>'EC','code_iso3'=>'ECU','nom'=>'Équateur','indicatif_telephone'=>'+593','drapeau_emoji'=>'🇪🇨','continent'=>'Amérique'],
            ['code_iso2'=>'BO','code_iso3'=>'BOL','nom'=>'Bolivie','indicatif_telephone'=>'+591','drapeau_emoji'=>'🇧🇴','continent'=>'Amérique'],
            ['code_iso2'=>'PY','code_iso3'=>'PRY','nom'=>'Paraguay','indicatif_telephone'=>'+595','drapeau_emoji'=>'🇵🇾','continent'=>'Amérique'],
            ['code_iso2'=>'UY','code_iso3'=>'URY','nom'=>'Uruguay','indicatif_telephone'=>'+598','drapeau_emoji'=>'🇺🇾','continent'=>'Amérique'],
            ['code_iso2'=>'GY','code_iso3'=>'GUY','nom'=>'Guyana','indicatif_telephone'=>'+592','drapeau_emoji'=>'🇬🇾','continent'=>'Amérique'],
            ['code_iso2'=>'SR','code_iso3'=>'SUR','nom'=>'Suriname','indicatif_telephone'=>'+597','drapeau_emoji'=>'🇸🇷','continent'=>'Amérique'],
            ['code_iso2'=>'PA','code_iso3'=>'PAN','nom'=>'Panama','indicatif_telephone'=>'+507','drapeau_emoji'=>'🇵🇦','continent'=>'Amérique'],
            ['code_iso2'=>'CR','code_iso3'=>'CRI','nom'=>'Costa Rica','indicatif_telephone'=>'+506','drapeau_emoji'=>'🇨🇷','continent'=>'Amérique'],
            ['code_iso2'=>'NI','code_iso3'=>'NIC','nom'=>'Nicaragua','indicatif_telephone'=>'+505','drapeau_emoji'=>'🇳🇮','continent'=>'Amérique'],
            ['code_iso2'=>'HN','code_iso3'=>'HND','nom'=>'Honduras','indicatif_telephone'=>'+504','drapeau_emoji'=>'🇭🇳','continent'=>'Amérique'],
            ['code_iso2'=>'SV','code_iso3'=>'SLV','nom'=>'Salvador','indicatif_telephone'=>'+503','drapeau_emoji'=>'🇸🇻','continent'=>'Amérique'],
            ['code_iso2'=>'GT','code_iso3'=>'GTM','nom'=>'Guatemala','indicatif_telephone'=>'+502','drapeau_emoji'=>'🇬🇹','continent'=>'Amérique'],
            ['code_iso2'=>'BZ','code_iso3'=>'BLZ','nom'=>'Belize','indicatif_telephone'=>'+501','drapeau_emoji'=>'🇧🇿','continent'=>'Amérique'],
            ['code_iso2'=>'CU','code_iso3'=>'CUB','nom'=>'Cuba','indicatif_telephone'=>'+53','drapeau_emoji'=>'🇨🇺','continent'=>'Amérique'],
            ['code_iso2'=>'DO','code_iso3'=>'DOM','nom'=>'République dominicaine','indicatif_telephone'=>'+1','drapeau_emoji'=>'🇩🇴','continent'=>'Amérique'],
            ['code_iso2'=>'HT','code_iso3'=>'HTI','nom'=>'Haïti','indicatif_telephone'=>'+509','drapeau_emoji'=>'🇭🇹','continent'=>'Amérique'],
            ['code_iso2'=>'JM','code_iso3'=>'JAM','nom'=>'Jamaïque','indicatif_telephone'=>'+1','drapeau_emoji'=>'🇯🇲','continent'=>'Amérique'],
            ['code_iso2'=>'TT','code_iso3'=>'TTO','nom'=>'Trinité-et-Tobago','indicatif_telephone'=>'+1','drapeau_emoji'=>'🇹🇹','continent'=>'Amérique'],
            ['code_iso2'=>'BS','code_iso3'=>'BHS','nom'=>'Bahamas','indicatif_telephone'=>'+1','drapeau_emoji'=>'🇧🇸','continent'=>'Amérique'],
            ['code_iso2'=>'BB','code_iso3'=>'BRB','nom'=>'Barbade','indicatif_telephone'=>'+1','drapeau_emoji'=>'🇧🇧','continent'=>'Amérique'],

            // ── ASIE ──
            ['code_iso2'=>'CN','code_iso3'=>'CHN','nom'=>'Chine','indicatif_telephone'=>'+86','drapeau_emoji'=>'🇨🇳','continent'=>'Asie'],
            ['code_iso2'=>'JP','code_iso3'=>'JPN','nom'=>'Japon','indicatif_telephone'=>'+81','drapeau_emoji'=>'🇯🇵','continent'=>'Asie'],
            ['code_iso2'=>'KR','code_iso3'=>'KOR','nom'=>'Corée du Sud','indicatif_telephone'=>'+82','drapeau_emoji'=>'🇰🇷','continent'=>'Asie'],
            ['code_iso2'=>'KP','code_iso3'=>'PRK','nom'=>'Corée du Nord','indicatif_telephone'=>'+850','drapeau_emoji'=>'🇰🇵','continent'=>'Asie'],
            ['code_iso2'=>'IN','code_iso3'=>'IND','nom'=>'Inde','indicatif_telephone'=>'+91','drapeau_emoji'=>'🇮🇳','continent'=>'Asie'],
            ['code_iso2'=>'PK','code_iso3'=>'PAK','nom'=>'Pakistan','indicatif_telephone'=>'+92','drapeau_emoji'=>'🇵🇰','continent'=>'Asie'],
            ['code_iso2'=>'BD','code_iso3'=>'BGD','nom'=>'Bangladesh','indicatif_telephone'=>'+880','drapeau_emoji'=>'🇧🇩','continent'=>'Asie'],
            ['code_iso2'=>'LK','code_iso3'=>'LKA','nom'=>'Sri Lanka','indicatif_telephone'=>'+94','drapeau_emoji'=>'🇱🇰','continent'=>'Asie'],
            ['code_iso2'=>'NP','code_iso3'=>'NPL','nom'=>'Népal','indicatif_telephone'=>'+977','drapeau_emoji'=>'🇳🇵','continent'=>'Asie'],
            ['code_iso2'=>'BT','code_iso3'=>'BTN','nom'=>'Bhoutan','indicatif_telephone'=>'+975','drapeau_emoji'=>'🇧🇹','continent'=>'Asie'],
            ['code_iso2'=>'AF','code_iso3'=>'AFG','nom'=>'Afghanistan','indicatif_telephone'=>'+93','drapeau_emoji'=>'🇦🇫','continent'=>'Asie'],
            ['code_iso2'=>'IR','code_iso3'=>'IRN','nom'=>'Iran','indicatif_telephone'=>'+98','drapeau_emoji'=>'🇮🇷','continent'=>'Asie'],
            ['code_iso2'=>'IQ','code_iso3'=>'IRQ','nom'=>'Irak','indicatif_telephone'=>'+964','drapeau_emoji'=>'🇮🇶','continent'=>'Asie'],
            ['code_iso2'=>'SY','code_iso3'=>'SYR','nom'=>'Syrie','indicatif_telephone'=>'+963','drapeau_emoji'=>'🇸🇾','continent'=>'Asie'],
            ['code_iso2'=>'TR','code_iso3'=>'TUR','nom'=>'Turquie','indicatif_telephone'=>'+90','drapeau_emoji'=>'🇹🇷','continent'=>'Asie'],
            ['code_iso2'=>'IL','code_iso3'=>'ISR','nom'=>'Israël','indicatif_telephone'=>'+972','drapeau_emoji'=>'🇮🇱','continent'=>'Asie'],
            ['code_iso2'=>'PS','code_iso3'=>'PSE','nom'=>'Palestine','indicatif_telephone'=>'+970','drapeau_emoji'=>'🇵🇸','continent'=>'Asie'],
            ['code_iso2'=>'JO','code_iso3'=>'JOR','nom'=>'Jordanie','indicatif_telephone'=>'+962','drapeau_emoji'=>'🇯🇴','continent'=>'Asie'],
            ['code_iso2'=>'LB','code_iso3'=>'LBN','nom'=>'Liban','indicatif_telephone'=>'+961','drapeau_emoji'=>'🇱🇧','continent'=>'Asie'],
            ['code_iso2'=>'SA','code_iso3'=>'SAU','nom'=>'Arabie saoudite','indicatif_telephone'=>'+966','drapeau_emoji'=>'🇸🇦','continent'=>'Asie'],
            ['code_iso2'=>'AE','code_iso3'=>'ARE','nom'=>'Émirats arabes unis','indicatif_telephone'=>'+971','drapeau_emoji'=>'🇦🇪','continent'=>'Asie'],
            ['code_iso2'=>'QA','code_iso3'=>'QAT','nom'=>'Qatar','indicatif_telephone'=>'+974','drapeau_emoji'=>'🇶🇦','continent'=>'Asie'],
            ['code_iso2'=>'BH','code_iso3'=>'BHR','nom'=>'Bahreïn','indicatif_telephone'=>'+973','drapeau_emoji'=>'🇧🇭','continent'=>'Asie'],
            ['code_iso2'=>'KW','code_iso3'=>'KWT','nom'=>'Koweït','indicatif_telephone'=>'+965','drapeau_emoji'=>'🇰🇼','continent'=>'Asie'],
            ['code_iso2'=>'OM','code_iso3'=>'OMN','nom'=>'Oman','indicatif_telephone'=>'+968','drapeau_emoji'=>'🇴🇲','continent'=>'Asie'],
            ['code_iso2'=>'YE','code_iso3'=>'YEM','nom'=>'Yémen','indicatif_telephone'=>'+967','drapeau_emoji'=>'🇾🇪','continent'=>'Asie'],
            ['code_iso2'=>'TH','code_iso3'=>'THA','nom'=>'Thaïlande','indicatif_telephone'=>'+66','drapeau_emoji'=>'🇹🇭','continent'=>'Asie'],
            ['code_iso2'=>'VN','code_iso3'=>'VNM','nom'=>'Viêt Nam','indicatif_telephone'=>'+84','drapeau_emoji'=>'🇻🇳','continent'=>'Asie'],
            ['code_iso2'=>'KH','code_iso3'=>'KHM','nom'=>'Cambodge','indicatif_telephone'=>'+855','drapeau_emoji'=>'🇰🇭','continent'=>'Asie'],
            ['code_iso2'=>'LA','code_iso3'=>'LAO','nom'=>'Laos','indicatif_telephone'=>'+856','drapeau_emoji'=>'🇱🇦','continent'=>'Asie'],
            ['code_iso2'=>'MM','code_iso3'=>'MMR','nom'=>'Birmanie','indicatif_telephone'=>'+95','drapeau_emoji'=>'🇲🇲','continent'=>'Asie'],
            ['code_iso2'=>'MY','code_iso3'=>'MYS','nom'=>'Malaisie','indicatif_telephone'=>'+60','drapeau_emoji'=>'🇲🇾','continent'=>'Asie'],
            ['code_iso2'=>'SG','code_iso3'=>'SGP','nom'=>'Singapour','indicatif_telephone'=>'+65','drapeau_emoji'=>'🇸🇬','continent'=>'Asie'],
            ['code_iso2'=>'ID','code_iso3'=>'IDN','nom'=>'Indonésie','indicatif_telephone'=>'+62','drapeau_emoji'=>'🇮🇩','continent'=>'Asie'],
            ['code_iso2'=>'PH','code_iso3'=>'PHL','nom'=>'Philippines','indicatif_telephone'=>'+63','drapeau_emoji'=>'🇵🇭','continent'=>'Asie'],
            ['code_iso2'=>'BN','code_iso3'=>'BRN','nom'=>'Brunei','indicatif_telephone'=>'+673','drapeau_emoji'=>'🇧🇳','continent'=>'Asie'],
            ['code_iso2'=>'TL','code_iso3'=>'TLS','nom'=>'Timor oriental','indicatif_telephone'=>'+670','drapeau_emoji'=>'🇹🇱','continent'=>'Asie'],
            ['code_iso2'=>'MN','code_iso3'=>'MNG','nom'=>'Mongolie','indicatif_telephone'=>'+976','drapeau_emoji'=>'🇲🇳','continent'=>'Asie'],
            ['code_iso2'=>'KZ','code_iso3'=>'KAZ','nom'=>'Kazakhstan','indicatif_telephone'=>'+7','drapeau_emoji'=>'🇰🇿','continent'=>'Asie'],
            ['code_iso2'=>'UZ','code_iso3'=>'UZB','nom'=>'Ouzbékistan','indicatif_telephone'=>'+998','drapeau_emoji'=>'🇺🇿','continent'=>'Asie'],
            ['code_iso2'=>'KG','code_iso3'=>'KGZ','nom'=>'Kirghizistan','indicatif_telephone'=>'+996','drapeau_emoji'=>'🇰🇬','continent'=>'Asie'],
            ['code_iso2'=>'TJ','code_iso3'=>'TJK','nom'=>'Tadjikistan','indicatif_telephone'=>'+992','drapeau_emoji'=>'🇹🇯','continent'=>'Asie'],
            ['code_iso2'=>'TM','code_iso3'=>'TKM','nom'=>'Turkménistan','indicatif_telephone'=>'+993','drapeau_emoji'=>'🇹🇲','continent'=>'Asie'],
            ['code_iso2'=>'GE','code_iso3'=>'GEO','nom'=>'Géorgie','indicatif_telephone'=>'+995','drapeau_emoji'=>'🇬🇪','continent'=>'Asie'],
            ['code_iso2'=>'AM','code_iso3'=>'ARM','nom'=>'Arménie','indicatif_telephone'=>'+374','drapeau_emoji'=>'🇦🇲','continent'=>'Asie'],
            ['code_iso2'=>'AZ','code_iso3'=>'AZE','nom'=>'Azerbaïdjan','indicatif_telephone'=>'+994','drapeau_emoji'=>'🇦🇿','continent'=>'Asie'],
            ['code_iso2'=>'MV','code_iso3'=>'MDV','nom'=>'Maldives','indicatif_telephone'=>'+960','drapeau_emoji'=>'🇲🇻','continent'=>'Asie'],
            ['code_iso2'=>'HK','code_iso3'=>'HKG','nom'=>'Hong Kong','indicatif_telephone'=>'+852','drapeau_emoji'=>'🇭🇰','continent'=>'Asie'],
            ['code_iso2'=>'MO','code_iso3'=>'MAC','nom'=>'Macao','indicatif_telephone'=>'+853','drapeau_emoji'=>'🇲🇴','continent'=>'Asie'],
            ['code_iso2'=>'TW','code_iso3'=>'TWN','nom'=>'Taïwan','indicatif_telephone'=>'+886','drapeau_emoji'=>'🇹🇼','continent'=>'Asie'],

            // ── OCÉANIE ──
            ['code_iso2'=>'AU','code_iso3'=>'AUS','nom'=>'Australie','indicatif_telephone'=>'+61','drapeau_emoji'=>'🇦🇺','continent'=>'Océanie'],
            ['code_iso2'=>'NZ','code_iso3'=>'NZL','nom'=>'Nouvelle-Zélande','indicatif_telephone'=>'+64','drapeau_emoji'=>'🇳🇿','continent'=>'Océanie'],
            ['code_iso2'=>'FJ','code_iso3'=>'FJI','nom'=>'Fidji','indicatif_telephone'=>'+679','drapeau_emoji'=>'🇫🇯','continent'=>'Océanie'],
            ['code_iso2'=>'PG','code_iso3'=>'PNG','nom'=>'Papouasie-Nouvelle-Guinée','indicatif_telephone'=>'+675','drapeau_emoji'=>'🇵🇬','continent'=>'Océanie'],
            ['code_iso2'=>'SB','code_iso3'=>'SLB','nom'=>'Salomon','indicatif_telephone'=>'+677','drapeau_emoji'=>'🇸🇧','continent'=>'Océanie'],
            ['code_iso2'=>'VU','code_iso3'=>'VUT','nom'=>'Vanuatu','indicatif_telephone'=>'+678','drapeau_emoji'=>'🇻🇺','continent'=>'Océanie'],
            ['code_iso2'=>'WS','code_iso3'=>'WSM','nom'=>'Samoa','indicatif_telephone'=>'+685','drapeau_emoji'=>'🇼🇸','continent'=>'Océanie'],
            ['code_iso2'=>'TO','code_iso3'=>'TON','nom'=>'Tonga','indicatif_telephone'=>'+676','drapeau_emoji'=>'🇹🇴','continent'=>'Océanie'],
            ['code_iso2'=>'KI','code_iso3'=>'KIR','nom'=>'Kiribati','indicatif_telephone'=>'+686','drapeau_emoji'=>'🇰🇮','continent'=>'Océanie'],
            ['code_iso2'=>'TV','code_iso3'=>'TUV','nom'=>'Tuvalu','indicatif_telephone'=>'+688','drapeau_emoji'=>'🇹🇻','continent'=>'Océanie'],
            ['code_iso2'=>'NR','code_iso3'=>'NRU','nom'=>'Nauru','indicatif_telephone'=>'+674','drapeau_emoji'=>'🇳🇷','continent'=>'Océanie'],
            ['code_iso2'=>'PW','code_iso3'=>'PLW','nom'=>'Palaos','indicatif_telephone'=>'+680','drapeau_emoji'=>'🇵🇼','continent'=>'Océanie'],
            ['code_iso2'=>'MH','code_iso3'=>'MHL','nom'=>'Îles Marshall','indicatif_telephone'=>'+692','drapeau_emoji'=>'🇲🇭','continent'=>'Océanie'],
            ['code_iso2'=>'FM','code_iso3'=>'FSM','nom'=>'Micronésie','indicatif_telephone'=>'+691','drapeau_emoji'=>'🇫🇲','continent'=>'Océanie'],
        ];

        $now = now();
        foreach ($pays as $row) {
            DB::table('intranet_pays')->updateOrInsert(
                ['code_iso2' => $row['code_iso2']],
                array_merge($row, ['created_at' => $now, 'updated_at' => $now])
            );
        }
    }
}
